export type Post = {
  id: string;
  title: string;
  content: string;
  createdAt: string;
  likes: number;
  type?: string; // e.g., 'confession', 'marketplace'
};

export type Follower = {
  id: string;
  name: string;
  campus?: string;
};

export type ProfileData = {
  id: string;
  name: string;
  email?: string;
  year?: string;
  major?: string;
  campus?: string;
  posts: Post[];
  followersCount: number;
  followers: Follower[];
  rating?: number; // 0-5
  reviews?: { id: string; author: string; text: string; rating: number }[];
};

import { supabase } from './supabaseClient';
// Mock implementation — replace with real API calls (supabase/fetch) later.
const wait = (ms = 300) => new Promise((r) => setTimeout(r, ms));

export async function fetchProfileData(userId?: string): Promise<ProfileData> {
  if (!userId) throw new Error('No userId provided');
  // Fetch profile from Supabase 'profiles' table
  const { data: profile, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', userId)
    .single();
  if (error || !profile) throw new Error('Profile not found');

  // Fetch posts
  const { data: posts, error: postsError } = await supabase
    .from('posts')
    .select('*')
    .eq('user_id', userId);
  if (postsError) throw new Error('Posts fetch error');

  // Fetch followers
  const { data: followers, error: followersError } = await supabase
    .from('followers')
    .select('id,name,campus')
    .eq('followed_id', userId);
  if (followersError) throw new Error('Followers fetch error');

  // Fetch reviews/ratings
  const { data: reviews, error: reviewsError } = await supabase
    .from('reviews')
    .select('id,author,text,rating')
    .eq('user_id', userId);
  if (reviewsError) throw new Error('Reviews fetch error');
  const rating = reviews && reviews.length > 0
    ? reviews.reduce((sum: number, r: any) => sum + r.rating, 0) / reviews.length
    : undefined;

  return {
    id: profile.id,
    name: profile.name,
    email: profile.email,
    year: profile.year,
    major: profile.major,
    campus: profile.campus,
    posts: posts ?? [],
    followersCount: followers?.length ?? 0,
    followers: followers ?? [],
    rating,
    reviews: reviews ?? [],
  };
  // @ts-ignore
  // eslint-disable-next-line
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
  // eslint-disable-next-line import/no-extraneous-dependencies
  // eslint-disable-next-line import/no-unassigned-import
  // eslint-disable-next-line import/no-unused-modules
  // eslint-disable-next-line import/no-unused-vars
  // eslint-disable-next-line import/no-named-as-default-member
  // eslint-disable-next-line import/no-named-as-default
  // eslint-disable-next-line import/no-named-default
  // eslint-disable-next-line import/no-named-export
  // eslint-disable-next-line import/no-duplicates
  // eslint-disable-next-line import/no-cycle
  // eslint-disable-next-line import/no-self-import
  // eslint-disable-next-line import/no-useless-path-segments
  // eslint-disable-next-line import/no-unresolved
  // eslint-disable-next-line import/no-absolute-path
  // eslint-disable-next-line import/no-relative-packages
}

export async function fetchUserPosts(userId?: string): Promise<Post[]> {
  const profile = await fetchProfileData(userId);
  return profile.posts;
}
